.TH "/Users/gerhard/Dropbox/FH-Gerhard/2.Semester_Gerhard/BETRIEBSSYSTEME/BETRIEBSSYSTEME_BSP1/BETRIEBSSYSTEME_BSP1 Directory Reference" 3 "Sat Feb 13 2016" "Version 0" "myfind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/gerhard/Dropbox/FH-Gerhard/2.Semester_Gerhard/BETRIEBSSYSTEME/BETRIEBSSYSTEME_BSP1/BETRIEBSSYSTEME_BSP1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
