.TH "/Users/gerhard/Dropbox/FH-Gerhard/2.Semester_Gerhard/BETRIEBSSYSTEME/BETRIEBSSYSTEME_BSP1/BETRIEBSSYSTEME_BSP1/main.c" 3 "Sat Feb 13 2016" "Version 0" "myfind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/gerhard/Dropbox/FH-Gerhard/2.Semester_Gerhard/BETRIEBSSYSTEME/BETRIEBSSYSTEME_BSP1/BETRIEBSSYSTEME_BSP1/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <grp\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <fnmatch\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUGLEVEL\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdo_file\fP (const char *file_name, const char *const *parms)"
.br
.ti -1c
.RI "\fBdo_dir\fP (const char *dir_name, const char *const *parms)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
myfind Beispiel 1
.PP
\fBAuthor:\fP
.RS 4
Karin Kalman karin.kalman@technikum-wien.at 
.PP
Michael Muellner michael.muellner@technikum-wien.at 
.PP
Gerhard Sabeditsch gerhard.sabeditsch@technikum-wien.at 
.RE
.PP
\fBDate:\fP
.RS 4
2016/02/13
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP
.RS 4
0 
.RE
.PP
.PP
URL: $HeadURL$
.PP
Last Modified: 
.PP
\fBAuthor\fP
.RS 4
Gerhard 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for myfind from the source code\&.
